on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  release:
    ## Only release on push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: npm ci  && npm run build
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  purge:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Purge package new version
        run: curl https://purge.jsdelivr.net/npm/@txtghana/enrich@${{ steps.package-version.outputs.current-version}}/dist/enrich.min.js
      - name: Force package latest version to use the just published version
        run: curl https://purge.jsdelivr.net/npm/@txtghana/enrich@latest/dist/enrich.min.js